[workspace]
resolver = "2"
members = [
    "crates/rlyeh-lexer",
    "crates/rlyeh-macro",
    "crates/rlyeh-parser",
    "crates/rlyeh-ast",
    "crates/rlyeh-hir",
    "crates/rlyeh-mir",
    "crates/rlyeh-lir",
    "crates/rlyeh-typecheck",
    "crates/rlyeh-desugar",
    "crates/rlyeh-borrowck",
    "crates/rlyeh-regionck",
    "crates/rlyeh-codegen",
    "crates/rlyeh-driver",
    "crates/rlyeh-std",
    "crates/rlyeh-actor-runtime",
    "crates/rlyeh-gc-runtime",
    "crates/rlyeh-region-alloc",
    "crates/rlyeh-lsp",
    "tools/rlyeh-fmt",
    "tools/rlyeh-check",
    "tools/rlyeh-doc",
    "tools/rlyeh-bench",
    "dagon",
]

# cargo-fuzz 的 fuzz crate 独立于工作区构建（需要 nightly）
exclude = ["crates/rlyeh-parser/fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://gitee.com/cathra/rlyeh-language.git"

[workspace.dependencies]
# 内部依赖
rlyeh-ast = { path = "crates/rlyeh-ast" }
rlyeh-hir = { path = "crates/rlyeh-hir" }
rlyeh-mir = { path = "crates/rlyeh-mir" }
rlyeh-lir = { path = "crates/rlyeh-lir" }
rlyeh-lexer = { path = "crates/rlyeh-lexer" }
rlyeh-macro = { path = "crates/rlyeh-macro" }
rlyeh-parser = { path = "crates/rlyeh-parser" }
rlyeh-typecheck = { path = "crates/rlyeh-typecheck" }
rlyeh-desugar = { path = "crates/rlyeh-desugar" }
rlyeh-borrowck = { path = "crates/rlyeh-borrowck" }
rlyeh-regionck = { path = "crates/rlyeh-regionck" }
rlyeh-codegen = { path = "crates/rlyeh-codegen" }
rlyeh-driver = { path = "crates/rlyeh-driver" }
rlyeh-std = { path = "crates/rlyeh-std" }
rlyeh-actor-runtime = { path = "crates/rlyeh-actor-runtime" }
rlyeh-gc-runtime = { path = "crates/rlyeh-gc-runtime" }
rlyeh-region-alloc = { path = "crates/rlyeh-region-alloc" }
rlyeh-lsp = { path = "crates/rlyeh-lsp" }
rlyeh-fmt = { path = "tools/rlyeh-fmt" }
rlyeh-check = { path = "tools/rlyeh-check" }
rlyeh-doc = { path = "tools/rlyeh-doc" }
rlyeh-bench = { path = "tools/rlyeh-bench" }
dagon = { path = "dagon" }

# 外部依赖
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
indexmap = "2"
once_cell = "1"
regex = "1"
log = "0"
env_logger = "0"
criterion = "0"
libfuzzer-sys = "0"
llvm-sys = "170"
cranelift = "0"
cranelift-module = "0"
cranelift-codegen = "0"
parking_lot = "0"
rayon = "1"
dashmap = "5"
pubgrub = "0"
toml = "0"
colored = "2"
libc = "0.2"
