[package]
name = "rlyeh-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rlyeh 编译器驱动：串联 lexer → parser → typecheck → borrowck → regionck → MIR → LIR → 代码生成，提供 rlyeh CLI"

[dependencies]
rlyeh-typecheck = { workspace = true }
rlyeh-borrowck = { workspace = true }
rlyeh-regionck = { workspace = true }
rlyeh-mir = { workspace = true }
rlyeh-lir = { workspace = true }
rlyeh-codegen = { workspace = true }
rlyeh-parser = { workspace = true }
rlyeh-ast = { workspace = true }
rlyeh-actor-runtime = { workspace = true }
rlyeh-fmt = { workspace = true }
rlyeh-check = { workspace = true }
rlyeh-doc = { workspace = true }
rlyeh-bench = { workspace = true }
rlyeh-lsp = { workspace = true }
rlyeh-region-alloc = { workspace = true }
dagon = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
