[package]
name = "rlyeh-lir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rlyeh 低级中间表示（LIR）：MIR → 三地址码 lowering 与类型推断"

[dependencies]
rlyeh-mir = { workspace = true }
rlyeh-hir = { workspace = true }

[dev-dependencies]
rlyeh-typecheck = { workspace = true }
