[package]
name = "rlyeh-typecheck"
version.workspace = true
edition.workspace = true

[dependencies]
rlyeh-ast = { workspace = true }
rlyeh-desugar = { workspace = true }
rlyeh-hir = { workspace = true }
rlyeh-lexer = { workspace = true }
rlyeh-parser = { workspace = true }
thiserror = { workspace = true }

[lib]
path = "src/lib.rs"
