[package]
name = "rlyeh-parser"
version.workspace = true
edition.workspace = true

[dependencies]
rlyeh-lexer = { workspace = true }
rlyeh-macro = { workspace = true }
rlyeh-ast = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "parser_bench"
harness = false
