[package]
name = "zeta-region-alloc"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "smart_bench"
harness = false

[lib]
path = "src/lib.rs"
# staticlib：供编译器生成的 LLVM 代码链接（L3 接线）
crate-type = ["rlib", "staticlib"]
